#server.port=8080

# JPA / HIBERNATE
spring.application.name=backend
spring.profiles.active=local
spring.jpa.show-sql=true

# SQLITE DATABASE
spring.datasource.url=${DB_URL:jdbc:sqlite:./matibabu-local.db}
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=validate

# FLYWAY

# Spring Session must NOT create its own tables.
# Flyway creates the Spring Session tables.
spring.session.jdbc.initialize-schema=never

# SPRING SESSION JDBC
# Store HttpSession in the database rather than application memory.
#spring.session.store-type=jdbc

# Default Spring Session table.
spring.session.jdbc.table-name=SPRING_SESSION

# Remove expired sessions every minute.
spring.session.jdbc.cleanup-cron=0 * * * * *

# SESSION TIMEOUT
# The Session expires after 30 minutes of inactivity.
server.servlet.session.timeout=30m

# SESSION COOKIE
# JavaScript cannot access JSESSIONID.
server.servlet.session.cookie.http-only=true

# Local development is HTTP.
# Set this to true when the application is deployed over HTTPS.
server.servlet.session.cookie.secure=false

# Reasonable default for a browser-based session.
server.servlet.session.cookie.same-site=lax

# LOGGING
logging.level.org.springframework.security=INFO